### ISSUE TITLE
Now stack trace

### ISSUE THREAD

**Issue by ezmiller** [axyjs/node-custom-errors#1]
Hi, this module looked to be exactly what I needed, but there doesn't seem to be any stack trace in the error it creates. Is this rectifiable?

**Comment by vasa-c** [comment]
Hi. Give an example, please.
My:
```javascript
var ce = require("node-custom-errors"),
    MyError = ce.create("MyError");

function x() {
    y();
}

function y() {
    throw new MyError("Oh, Error!");
}

x();
```
Output:
```
/node-custom-errors/test/index.js:9
    throw new MyError("Oh, Error!");
          ^
MyError: Oh, Error!
    at y (/node-custom-errors/test/index.js:9:11)
    at x (/node-custom-errors/test/index.js:5:5)
    at Object.<anonymous> (/node-custom-errors/test/index.js:12:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

It work.

node 0.10.33
