### ISSUE TITLE
This module does not work with node 0.12.x

### ISSUE THREAD

**Issue by fedescarpa** [axyjs/node-custom-errors#2]
```js
> var nce = require('node-custom-errors')
TypeError: Cannot assign to read only property 'name' of function CustomError(message) {
        Error.call(this);
        Error.captureStackTrace(this, CustomError);
 ...<omitted>... }
    at create (/home/federico/Workspace/js/node-friendly-response/node_modules/node-custom-errors/index.js:65:22)
    at create (/home/federico/Workspace/js/node-friendly-response/node_modules/node-custom-errors/index.js:31:16)
    at Object.<anonymous> (/home/federico/Workspace/js/node-friendly-response/node_modules/node-custom-errors/index.js:120:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at repl:1:11
```

**Comment by vasa-c** [comment]
fedescarpa, thanx!
Fixed.
