### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by nbasov** [axyjs/node-custom-errors#3]
Hello,

Got following error 

```
$ node test.js 
{ [SapError] inner: 'err', context: 'context' }
/home/z00100/Documents/aks/aks-transition-web/node_modules/node-custom-errors/index.js:83
    parent: function parent() {
                           ^

RangeError: Maximum call stack size exceeded
    at CustomError.parent (/home/z00100/Documents/aks/aks-transition-web/node_modules/node-custom-errors/index.js:83:28)
    at CustomError.customErrors.create.construct (/home/z00100/Documents/aks/aks-transition-web/test.js:17:14)
    at CustomError.parent (/home/z00100/Documents/aks/aks-transition-web/node_modules/node-custom-errors/index.js:88:30)
    at CustomError.customErrors.create.construct (/home/z00100/Documents/aks/aks-transition-web/test.js:17:14)
    at CustomError.parent (/home/z00100/Documents/aks/aks-transition-web/node_modules/node-custom-errors/index.js:88:30)
    at CustomError.customErrors.create.construct (/home/z00100/Documents/aks/aks-transition-web/test.js:17:14)
    at CustomError.parent (/home/z00100/Documents/aks/aks-transition-web/node_modules/node-custom-errors/index.js:88:30)
    at CustomError.customErrors.create.construct (/home/z00100/Documents/aks/aks-transition-web/test.js:17:14)
    at CustomError.parent (/home/z00100/Documents/aks/aks-transition-web/node_modules/node-custom-errors/index.js:88:30)
    at CustomError.customErrors.create.construct (/home/z00100/Documents/aks/aks-transition-web/test.js:17:14)
```

with this code:

```
'use strict';

var customErrors = require('node-custom-errors');

var BaseError = customErrors.create({
    name: 'BaseError',
    abstract: true,
    construct: function (err) {
        this.inner = err;
    }
});

var SapError = customErrors.create({
    name: 'SapError',
    parent: BaseError,
    construct: function (err, context) {
        this.parent(err);
        this.context = context || undefined;
    }
});

var SapOperationError = customErrors.create({
    name: 'SapOperationError',
    parent: SapError,
    construct: function (err, context, errors) {
        this.parent(err);
        this.errors = errors || undefined;
    }
});

console.log(new SapError('err', 'context'));
console.log(new SapOperationError('err', 'context', []));
```
 
As you see, error with 1 inheritance level (SapError) works well. Error with 2 level (SapOperationError) caused "RangeError: Maximum call stack size exceeded". 

node.js: 5.9.1

**Comment by vasa-c** [comment]
Thanks, @nbasov .

this.parent doesn't work for multi-level inheritance.
Use `BaseClass.init()`: https://github.com/axyjs/node-custom-errors/wiki/en-create#inheritance-custom-constructor
